# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  run:
    desc: run app
    cmds:
      - golangci-lint fmt
      - golangci-lint run
      - go run .
    silent: false

  add:
    cmds:
      - golangci-lint fmt
      - golangci-lint run
      - go mod tidy
      - git add .
